### ISSUE TITLE
캠페인 카드에 대한 내용 제공 API 구현

### ISSUE THREAD

**Issue by TeackH** [dev4jaehunkim/chaination#41]
### 기능 설명

캠페인 카드에 대한 내용을 Supabase에서 가져와 API로 제공시키도록 하는 기능 구현

### 요구사항

Supabase에 있는 데이터를 JS로 불러와 상세 페이지와 캠페인 카드 내부의 내용이 불러와지도록 구현 되어야 합니다

**Comment by Saelma** [comment]
Feat #50 작업 완료로 인한 해당 이슈 완료
